"""
California POST + CDCR officer employment index cleaner.

Two source files:
  1. CPRA_R000301-011425__ADHOC-809.xlsx   — LEO data (POST)
  2. PDSQ118B-C_CDCR Appts&Seps 2005-2023_Final.csv — Corrections (CDCR)

Output: output/ca_index.csv
"""

import argparse
import os
import re

import pandas as pd
from nameparser import HumanName

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser()
parser.add_argument("--input-dir", default="data/input")
parser.add_argument("--output-dir", default="output")
args = parser.parse_args()

INPUT_DIR = args.input_dir
OUTPUT_DIR = args.output_dir
os.makedirs(OUTPUT_DIR, exist_ok=True)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def safe_date(val):
    """Return YYYY-MM-DD string or empty string for invalid/missing dates."""
    s = str(val).strip()
    if not s or s in ("nan", "NaT", "None", "0000-00-00", "00/00/0000", "NaN"):
        return ""
    try:
        parsed = pd.to_datetime(s, errors="coerce")
        if pd.isna(parsed):
            return ""
        return parsed.strftime("%Y-%m-%d")
    except Exception:
        return ""

# ---------------------------------------------------------------------------
# Separation code → human-readable reason (derived from groundtruth)
# ---------------------------------------------------------------------------
SEPARATION_CODE_MAP = {
    "1":  "Resigned",
    "2":  "Discharged",
    "3":  "Retired",
    "4":  "Deceased",
    "5":  "Felony",
    "6":  "Other",
    "7":  "Promotion/Demotion",
    "8":  "Involuntary Separation",
    "9":  "Separated Pending Complaint, Administrative Charge, or Investigation for Serious Misconduct",
    "10": "Status Change",
    "11": "Did Not Complete Probation",
    "Z":  "Unknown",
    "":   "Other",
}

# ---------------------------------------------------------------------------
# LEO agency name lookup (input raw name → canonical name)
# Built from groundtruth comparison; covers 787 known agencies.
# For unmapped agencies we fall back to rule-based expansion.
# ---------------------------------------------------------------------------
LEO_AGENCY_MAP = {
    "ADELANTO PD": "ADELANTO POLICE DEPARTMENT",
    "ALAMEDA CO CORONER  C-01": "ALAMEDA COUNTY SHERIFF'S DEPARTMENT/CORONER",
    "ALAMEDA CO DA - INSPECTORS DIVISION": "ALAMEDA COUNTY DISTRICT ATTORNEY - INSPECTORS DIVISION",
    "ALAMEDA CO SD/CORONER": "ALAMEDA COUNTY SHERIFF'S DEPARTMENT/CORONER",
    "ALAMEDA PD": "ALAMEDA POLICE DEPARTMENT",
    "ALAMEDA/CONTRA COSTA TRAN": "ALAMEDA/CONTRA COSTA TRAN",
    "ALBANY PD": "ALBANY POLICE DEPARTMENT",
    "ALHAMBRA PD": "ALHAMBRA POLICE DEPARTMENT",
    "ALLAN HANCOCK CCD PD": "ALLAN HANCOCK COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT",
    "ALPINE CO SO": "ALPINE COUNTY SHERIFF'S OFFICE",
    "ALTURAS PD": "ALTURAS POLICE DEPARTMENT",
    "AMADOR CO DA": "AMADOR COUNTY DISTRICT ATTORNEY",
    "AMADOR CO SO/CORONER": "AMADOR COUNTY SHERIFF'S OFFICE/CORONER",
    "AMTRAK PD": "AMTRAK POLICE DEPARTMENT",
    "ANAHEIM PD": "ANAHEIM POLICE DEPARTMENT",
    "ANDERSON PD": "ANDERSON POLICE DEPARTMENT",
    "ANGELS CAMP PD": "ANGELS CAMP POLICE DEPARTMENT",
    "ANTIOCH PD": "ANTIOCH POLICE DEPARTMENT",
    "APPLE VALLEY UNIF SCH DIST PD": "APPLE VALLEY UNIFIED SCH DISTRICT POLICE DEPARTMENT",
    "ARCADIA PD": "ARCADIA POLICE DEPARTMENT",
    "ARCATA PD": "ARCATA POLICE DEPARTMENT",
    "ARROYO GRANDE PD": "ARROYO GRANDE POLICE DEPARTMENT",
    "ARVIN PD": "ARVIN POLICE DEPARTMENT",
    "ATASCADERO PD": "ATASCADERO POLICE DEPARTMENT",
    "ATHERTON PD": "ATHERTON POLICE DEPARTMENT",
    "ATWATER PD": "ATWATER POLICE DEPARTMENT",
    "AUBURN PD": "AUBURN POLICE DEPARTMENT",
    "AVENAL PD": "AVENAL POLICE DEPARTMENT",
    "AZUSA PD": "AZUSA POLICE DEPARTMENT",
    "BAKERSFIELD PD": "BAKERSFIELD POLICE DEPARTMENT",
    "BALDWIN PARK PD": "BALDWIN PARK POLICE DEPARTMENT",
    "BALDWIN PARK USD PD": "BALDWIN PARK UNIFIED SCHOOL DISTRICT POLICE DEPARTMENT",
    "BANNING PD": "BANNING POLICE DEPARTMENT",
    "BARSTOW PD": "BARSTOW POLICE DEPARTMENT",
    "BAY AREA RAPID TRANSIT PD": "BAY AREA RAPID TRANSIT POLICE DEPARTMENT",
    "BEAR VALLEY PD": "BEAR VALLEY POLICE DEPARTMENT",
    "BEAUMONT PD": "BEAUMONT POLICE DEPARTMENT",
    "BELL GARDENS PD": "BELL GARDENS POLICE DEPARTMENT",
    "BELL PD": "BELL POLICE DEPARTMENT",
    "BELMONT PD": "BELMONT POLICE DEPARTMENT",
    "BELVEDERE PD": "BELVEDERE POLICE DEPARTMENT",
    "BENICIA PD": "BENICIA POLICE DEPARTMENT",
    "BERKELEY PD": "BERKELEY POLICE DEPARTMENT",
    "BEVERLY HILLS PD": "BEVERLY HILLS POLICE DEPARTMENT",
    "BIGGS PD  C-04": "BIGGS POLICE DEPARTMENT C-04",
    "BISHOP PD": "BISHOP POLICE DEPARTMENT",
    "BLUE LAKE PD": "BLUE LAKE POLICE DEPARTMENT",
    "BLYTHE PD": "BLYTHE POLICE DEPARTMENT",
    "BRAWLEY PD": "BRAWLEY POLICE DEPARTMENT",
    "BREA 911 COMM CTR": "BREA 911 COMM CTR",
    "BREA PD": "BREA POLICE DEPARTMENT",
    "BRENTWOOD PD": "BRENTWOOD POLICE DEPARTMENT",
    "BRISBANE PD": "BRISBANE POLICE DEPARTMENT",
    "BROADMOOR PD": "BROADMOOR POLICE DEPARTMENT",
    "BUENA PARK PD": "BUENA PARK POLICE DEPARTMENT",
    "BURBANK AIRPORT AUTH PD": "BURBANK AIRPORT AUTH POLICE DEPARTMENT",
    "BURBANK PD": "BURBANK POLICE DEPARTMENT",
    "BURLINGAME PD": "BURLINGAME POLICE DEPARTMENT",
    "BURLINGTON NORTHRN SANTA FE RR": "BURLINGTON NORTHRN SANTA FE RR",
    "BUTTE CCD PD": "BUTTE COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT",
    "BUTTE CO DA": "BUTTE COUNTY DISTRICT ATTORNEY",
    "BUTTE CO SO/CORONER": "BUTTE COUNTY SHERIFF'S OFFICE/CORONER",
    "CA ALCOHOLIC BEVERAGE CONTROL": "CALIFORNIA ALCOHOLIC BEVERAGE CONTROL",
    "CA ASSEMBLY SGT AT ARMS LEGIS": "CALIFORNIA ASSEMBLY SGT AT ARMS LEGIS",
    "CA DEPT CANNABIS CNTL, ENF DIV": "CALIFORNIA DEPARTMENT CANNABIS CNTL, ENFORCEMENT DIVISION",
    "CA DEPT CONSUMER AFF CSLB (NON-POST)": "CALIFORNIA DEPARTMENT CONSUMER AFF CSLB (NON-POST)",
    "CA DEPT CONSUMER AFF DEN BD": "CALIFORNIA DEPARTMENT CONSUMER AFF DEN BD",
    "CA DEPT CONSUMER AFF INVEST": "CALIFORNIA DEPARTMENT CONSUMER AFF INVEST",
    "CA DEPT CONSUMER AFF MED": "CALIFORNIA DEPARTMENT CONSUMER AFF MED",
    "CA DEPT DEVELOPMENTAL INV": "CALIFORNIA DEPARTMENT DEVELOPMENTAL INV",
    "CA DEPT DEVELOPMENTAL OPS": "CALIFORNIA DEPARTMENT DEVELOPMENTAL OPS",
    "CA DEPT DEVELOPMENTAL PD": "CALIFORNIA DEPARTMENT DEVELOPMENTAL POLICE DEPARTMENT",
    "CA DEPT EMPLOYMENT DEVELOPMENT": "CALIFORNIA DEPARTMENT EMPLOYMENT DEVELOPMENT",
    "CA DEPT FISH & WILDLIFE": "CALIFORNIA DEPARTMENT FISH & WILDLIFE",
    "CA DEPT HEALTH CARE SVCS": "CALIFORNIA DEPARTMENT HEALTH CARE SERVICES",
    "CA DEPT INDUSTRIAL RELATIONS": "CALIFORNIA DEPARTMENT INDUSTRIAL RELATIONS",
    "CA DEPT INSURANCE FRAUD": "CALIFORNIA DEPARTMENT INSURANCE FRAUD",
    "CA DEPT JUSTICE": "CALIFORNIA DEPARTMENT JUSTICE",
    "CA DEPT MOTOR VEHICLES": "CALIFORNIA DEPARTMENT MOTOR VEHICLES",
    "CA DEPT OF FIN PROT AND INNOV": "CALIFORNIA DEPARTMENT OF FIN PROT AND INNOV",
    "CA DEPT OF MNGD HEALTHCARE": "CALIFORNIA DEPARTMENT OF MNGD HEALTHCARE",
    "CA DEPT PARKS & RECREATION": "CALIFORNIA DEPARTMENT PARKS & RECREATION",
    "CA DEPT PUB HEALTH FOOD/DRUG": "CALIFORNIA DEPARTMENT PUBLIC HEALTH FOOD/DRUG",
    "CA DEPT PUB HEALTH YTH TOB ENF": "CALIFORNIA DEPARTMENT PUBLIC HEALTH YOUTH TOB ENFORCEMENT",
    "CA DEPT SOCIAL SERVICES": "CALIFORNIA DEPARTMENT SOCIAL SERVICES",
    "CA DEPT STATE HOSPITALS – OFC OF SPEC INVEST": "CALIFORNIA DEPARTMENT STATE HOSPITALS – OFFICE OF SPEC INVEST",
    "CA DEPT TOXIC SUBSTANCES CNTL": "CALIFORNIA DEPARTMENT TOXIC SUBSTANCES CNTL",
    "CA DOJ, GAMBLING CNTRL": "CALIFORNIA DOJ, GAMBLING CNTRL",
    "CA DOJ, MEDI-CAL FRAUD": "CALIFORNIA DOJ, MEDI-CAL FRAUD",
    "CA FRANCHISE TAX BOARD": "CALIFORNIA FRANCHISE TAX BOARD",
    "CA HIGHWAY PATROL": "CALIFORNIA HIGHWAY PATROL",
    "CA HORSE RACING BOARD": "CALIFORNIA HORSE RACING BOARD",
    "CA OFFICE OF LE SUPPORT (OLES)": "CALIFORNIA OFFICE OF LE SUPPORT (OLES)",
    "CA SECRETARY OF STATE OFC INV": "CALIFORNIA SECRETARY OF STATE OFFICE INV",
    "CA ST CONTROLLER - INV": "CALIFORNIA ST CONTROLLER - INV",
    "CA STATE FAIR PD": "CALIFORNIA STATE FAIR POLICE DEPARTMENT",
    "CA STATE FIRE MARSHAL": "CALIFORNIA STATE FIRE MARSHAL",
    "CA STATE LOTTERY": "CALIFORNIA STATE LOTTERY",
    "CA STATE POLICE C-34": "CALIFORNIA STATE POLICE C-34",
    "CABRILLO COMM COLLEGE": "CABRILLO COMM COLLEGE",
    "CAL - OES": "CAL - OES",
    "CAL FIRE": "CAL FIRE",
    "CAL FIRE - OFFICE OF STATE FIRE MARSHAL": "CAL FIRE - OFFICE OF STATE FIRE MARSHAL",
    "CALAVERAS CO DA": "CALAVERAS COUNTY DISTRICT ATTORNEY",
    "CALAVERAS CO SD": "CALAVERAS COUNTY SHERIFF'S DEPARTMENT",
    "CALEXICO PD": "CALEXICO POLICE DEPARTMENT",
    "CALIFORNIA CITY PD": "CALIFORNIA CITY POLICE DEPARTMENT",
    "CALIPATRIA PD": "CALIPATRIA POLICE DEPARTMENT",
    "CALISTOGA PD": "CALISTOGA POLICE DEPARTMENT",
    "CAMPBELL PD": "CAMPBELL POLICE DEPARTMENT",
    "CAPITOLA PD": "CAPITOLA POLICE DEPARTMENT",
    "CARLSBAD PD": "CARLSBAD POLICE DEPARTMENT",
    "CARMEL PD": "CARMEL POLICE DEPARTMENT",
    "CARPINTERIA PD  C-42": "CARPINTERIA POLICE DEPARTMENT C-42",
    "CATHEDRAL CITY PD": "CATHEDRAL CITY POLICE DEPARTMENT",
    "CENTRAL MARIN POLICE AUTHORITY": "CENTRAL MARIN POLICE AUTHORITY",
    "CERES DPS": "CERES DEPARTMENT OF PUBLIC SAFETY",
    "CERRITOS COLLEGE POLICE DEPARTMENT": "CERRITOS COLLEGE POLICE DEPARTMENT",
    "CERRITOS PD": "CERRITOS POLICE DEPARTMENT",
    "CHAFFEY CCD PD": "CHAFFEY COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT",
    "CHICO PD": "CHICO POLICE DEPARTMENT",
    "CHINA LAKE PD": "CHINA LAKE POLICE DEPARTMENT",
    "CHINO PD": "CHINO POLICE DEPARTMENT",
    "CHOWCHILLA PD": "CHOWCHILLA POLICE DEPARTMENT",
    "CHULA VISTA PD": "CHULA VISTA POLICE DEPARTMENT",
    "CITRUS HEIGHTS PD": "CITRUS HEIGHTS POLICE DEPARTMENT",
    "CITY OF SACRAMENTO PARK RANGERS": "CITY OF SACRAMENTO PARK RANGERS",
    "CLAREMONT PD": "CLAREMONT POLICE DEPARTMENT",
    "CLAYTON PD": "CLAYTON POLICE DEPARTMENT",
    "CLEARLAKE PD": "CLEARLAKE POLICE DEPARTMENT",
    "CLOVERDALE PD": "CLOVERDALE POLICE DEPARTMENT",
    "CLOVIS PD": "CLOVIS POLICE DEPARTMENT",
    "CLOVIS UNIF SCHL DIST PD": "CLOVIS UNIFIED SCHOOL DISTRICT POLICE DEPARTMENT",
    "COACHELLA PD": "COACHELLA POLICE DEPARTMENT",
    "COALINGA PD": "COALINGA POLICE DEPARTMENT",
    "COAST CCD PD": "COAST COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT",
    "COLFAX PD": "COLFAX POLICE DEPARTMENT",
    "COLLEGE OF THE REDWOODS PD": "COLLEGE OF THE REDWOODS POLICE DEPARTMENT",
    "COLLEGE OF THE SEQUOIAS PD": "COLLEGE OF THE SEQUOIAS POLICE DEPARTMENT",
    "COLMA PD": "COLMA POLICE DEPARTMENT",
    "COLTON PD": "COLTON POLICE DEPARTMENT",
    "COLUSA CO DISTRICT ATTORNEY": "COLUSA COUNTY DISTRICT ATTORNEY",
    "COLUSA COUNTY SD": "COLUSA COUNTY SHERIFF'S DEPARTMENT",
    "COLUSA PD": "COLUSA POLICE DEPARTMENT",
    "COMPTON CCD PD": "COMPTON COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT",
    "COMPTON PD": "COMPTON POLICE DEPARTMENT",
    "COMPTON UNIF SCH DIST PD": "COMPTON UNIFIED SCH DISTRICT POLICE DEPARTMENT",
    "CONCORD PD": "CONCORD POLICE DEPARTMENT",
    "CONTRA COSTA CCD PD": "CONTRA COSTA COMMUNITY COLLEGE DISTRICT POLICE DEPARTMENT",
    "CONTRA COSTA CO DA": "CONTRA COSTA COUNTY DISTRICT ATTORNEY",
    "CONTRA COSTA CO MARSHAL": "CONTRA COSTA COUNTY MARSHAL",
    "CONTRA COSTA CO SO/CORONER": "CONTRA COSTA COUNTY SHERIFF'S OFFICE/CORONER",
    "CORCORAN PD": "CORCORAN POLICE DEPARTMENT",
    "CORNING PD": "CORNING POLICE DEPARTMENT",
    "CORONA PD": "CORONA POLICE DEPARTMENT",
    "CORONADO PD": "CORONADO POLICE DEPARTMENT",
    "CORTE MADERA PD  C-21": "CORTE MADERA POLICE DEPARTMENT C-21",
    "COSTA MESA COMM DEPT": "COSTA MESA COMM DEPARTMENT",
    "COSTA MESA PD": "COSTA MESA POLICE DEPARTMENT",
    "COTATI PD": "COTATI POLICE DEPARTMENT",
    "COVINA PD": "COVINA POLICE DEPARTMENT",
    "CPSU SAN LUIS OBISPO PD": "CPSU SAN LUIS OBISPO POLICE DEPARTMENT",
    "CRESCENT CITY PD": "CRESCENT CITY POLICE DEPARTMENT",
    "CSU BAKERSFIELD DPS": "CALIFORNIA STATE UNIVERSITY BAKERSFIELD DEPARTMENT OF PUBLIC SAFETY",
    "CSU CAL MARITIME ACADEMY PD": "CALIFORNIA STATE UNIVERSITY CAL MARITIME ACADEMY POLICE DEPARTMENT",
    "CSU CHANNEL ISLANDS PD": "CALIFORNIA STATE UNIVERSITY CHANNEL ISLANDS POLICE DEPARTMENT",
    "CSU CHICO PD": "CALIFORNIA STATE UNIVERSITY CHICO POLICE DEPARTMENT",
    "CSU DOMINGUEZ HILLS PD": "CALIFORNIA STATE UNIVERSITY DOMINGUEZ HILLS POLICE DEPARTMENT",
    "CSU EAST BAY PD": "CALIFORNIA STATE UNIVERSITY EAST BAY POLICE DEPARTMENT",
    "CSU FRESNO DPS": "CALIFORNIA STATE UNIVERSITY FRESNO DEPARTMENT OF PUBLIC SAFETY",
    "CSU FULLERTON PD": "CALIFORNIA STATE UNIVERSITY FULLERTON POLICE DEPARTMENT",
    "CSU HUMBOLDT PD": "CALIFORNIA STATE UNIVERSITY HUMBOLDT POLICE DEPARTMENT",
    "CSU LONG BEACH PD": "CALIFORNIA STATE UNIVERSITY LONG BEACH POLICE DEPARTMENT",
    "CSU LOS ANGELES DPS": "CALIFORNIA STATE UNIVERSITY LOS ANGELES DEPARTMENT OF PUBLIC SAFETY",
    "CSU MONTEREY BAY PD": "CALIFORNIA STATE UNIVERSITY MONTEREY BAY POLICE DEPARTMENT",
    "CSU NORTHRIDGE DEPT POLICE SVS": "CALIFORNIA STATE UNIVERSITY NORTHRIDGE DEPARTMENT POLICE SERVICES",
    "CSU POMONA DPS": "CALIFORNIA STATE UNIVERSITY POMONA DEPARTMENT OF PUBLIC SAFETY",
    "CSU SACRAMENTO PD": "CALIFORNIA STATE UNIVERSITY SACRAMENTO POLICE DEPARTMENT",
    "CSU SAN BERNARDINO PD": "CALIFORNIA STATE UNIVERSITY SAN BERNARDINO POLICE DEPARTMENT",
    "CSU SAN DIEGO PD": "CALIFORNIA STATE UNIVERSITY SAN DIEGO POLICE DEPARTMENT",
    "CSU SAN FRANCISCO PD": "CALIFORNIA STATE UNIVERSITY SAN FRANCISCO POLICE DEPARTMENT",
    "CSU SAN JOSE PD": "CALIFORNIA STATE UNIVERSITY SAN JOSE POLICE DEPARTMENT",
    "CSU SAN MARCOS PD": "CALIFORNIA STATE UNIVERSITY SAN MARCOS POLICE DEPARTMENT",
    "CSU SONOMA PD": "CALIFORNIA STATE UNIVERSITY SONOMA POLICE DEPARTMENT",
    "CSU STANISLAUS DPS": "CALIFORNIA STATE UNIVERSITY STANISLAUS DEPARTMENT OF PUBLIC SAFETY",
    "CUESTA CC PD": "CUESTA CC POLICE DEPARTMENT",
    "CULVER CITY PD": "CULVER CITY POLICE DEPARTMENT",
    "CYPRESS PD": "CYPRESS POLICE DEPARTMENT",
    "DALY CITY PD": "DALY CITY POLICE DEPARTMENT",
    "DAVIS PD": "DAVIS POLICE DEPARTMENT",
    "DEL NORTE CO DA": "DEL NORTE COUNTY DISTRICT ATTORNEY",
    "DEL NORTE COUNTY SO": "DEL NORTE COUNTY SHERIFF'S OFFICE",
    "DEL REY OAKS PD": "DEL REY OAKS POLICE DEPARTMENT",
    "DELANO PD": "DELANO POLICE DEPARTMENT",
    "DESERT HOT SPRINGS  PD": "DESERT HOT SPRINGS POLICE DEPARTMENT",
    "DINUBA PD": "DINUBA POLICE DEPARTMENT",
    "DIXON PD": "DIXON POLICE DEPARTMENT",
    "DOJ MEDI-CAL FRAUD/ELDER ABUSE": "DOJ MEDI-CAL FRAUD/ELDER ABUSE",
    "DOWNEY PD": "DOWNEY POLICE DEPARTMENT",
    "DUARTE PD": "DUARTE POLICE DEPARTMENT",
    "EL CAJON PD": "EL CAJON POLICE DEPARTMENT",
    "EL CENTRO PD": "EL CENTRO POLICE DEPARTMENT",
    "EL CERRITO PD": "EL CERRITO POLICE DEPARTMENT",
    "EL DORADO CO SO": "EL DORADO COUNTY SHERIFF'S OFFICE",
    "EL MONTE PD": "EL MONTE POLICE DEPARTMENT",
    "EL SEGUNDO PD": "EL SEGUNDO POLICE DEPARTMENT",
    "ELK GROVE PD": "ELK GROVE POLICE DEPARTMENT",
    "EMERYVILLE PD": "EMERYVILLE POLICE DEPARTMENT",
    "ENCINITAS PD": "ENCINITAS POLICE DEPARTMENT",
    "ESCALON PD": "ESCALON POLICE DEPARTMENT",
    "ESCONDIDO PD": "ESCONDIDO POLICE DEPARTMENT",
    "EUREKA PD": "EUREKA POLICE DEPARTMENT",
    "FAIRFIELD PD": "FAIRFIELD POLICE DEPARTMENT",
    "FARMERSVILLE PD": "FARMERSVILLE POLICE DEPARTMENT",
    "FILLMORE PD": "FILLMORE POLICE DEPARTMENT",
    "FOLSOM PD": "FOLSOM POLICE DEPARTMENT",
    "FONTANA PD": "FONTANA POLICE DEPARTMENT",
    "FORT BRAGG PD": "FORT BRAGG POLICE DEPARTMENT",
    "FOSTER CITY PD": "FOSTER CITY POLICE DEPARTMENT",
    "FOUNTAIN VALLEY PD": "FOUNTAIN VALLEY POLICE DEPARTMENT",
    "FREMONT PD": "FREMONT POLICE DEPARTMENT",
    "FRESNO CO DA": "FRESNO COUNTY DISTRICT ATTORNEY",
    "FRESNO CO SD": "FRESNO COUNTY SHERIFF'S DEPARTMENT",
    "FRESNO PD": "FRESNO POLICE DEPARTMENT",
    "FULLERTON PD": "FULLERTON POLICE DEPARTMENT",
    "GALT PD": "GALT POLICE DEPARTMENT",
    "GARDENA PD": "GARDENA POLICE DEPARTMENT",
    "GILROY PD": "GILROY POLICE DEPARTMENT",
    "GLENDALE PD": "GLENDALE POLICE DEPARTMENT",
    "GLENDORA PD": "GLENDORA POLICE DEPARTMENT",
    "GONZALES PD": "GONZALES POLICE DEPARTMENT",
    "GRASS VALLEY PD": "GRASS VALLEY POLICE DEPARTMENT",
    "GRIDLEY PD": "GRIDLEY POLICE DEPARTMENT",
    "GROVER BEACH PD": "GROVER BEACH POLICE DEPARTMENT",
    "GUADALUPE PD": "GUADALUPE POLICE DEPARTMENT",
    "HALF MOON BAY PD": "HALF MOON BAY POLICE DEPARTMENT",
    "HANFORD PD": "HANFORD POLICE DEPARTMENT",
    "HAWTHORNE PD": "HAWTHORNE POLICE DEPARTMENT",
    "HAYWARD PD": "HAYWARD POLICE DEPARTMENT",
    "HEALDSBURG PD": "HEALDSBURG POLICE DEPARTMENT",
    "HEMET PD": "HEMET POLICE DEPARTMENT",
    "HERCULES PD": "HERCULES POLICE DEPARTMENT",
    "HESPERIA PD": "HESPERIA POLICE DEPARTMENT",
    "HILLSBOROUGH PD": "HILLSBOROUGH POLICE DEPARTMENT",
    "HOLLISTER PD": "HOLLISTER POLICE DEPARTMENT",
    "HUNTINGTON BEACH PD": "HUNTINGTON BEACH POLICE DEPARTMENT",
    "HUNTINGTON PARK PD": "HUNTINGTON PARK POLICE DEPARTMENT",
    "IMPERIAL CO SD": "IMPERIAL COUNTY SHERIFF'S DEPARTMENT",
    "IMPERIAL PD": "IMPERIAL POLICE DEPARTMENT",
    "INDIO PD": "INDIO POLICE DEPARTMENT",
    "INGLEWOOD PD": "INGLEWOOD POLICE DEPARTMENT",
    "IRVINE PD": "IRVINE POLICE DEPARTMENT",
    "IRWINDALE PD": "IRWINDALE POLICE DEPARTMENT",
    "JACKSON PD": "JACKSON POLICE DEPARTMENT",
    "KERMAN PD": "KERMAN POLICE DEPARTMENT",
    "KERN COUNTY SO": "KERN COUNTY SHERIFF'S OFFICE",
    "KING CITY PD": "KING CITY POLICE DEPARTMENT",
    "KINGS CO DA": "KINGS COUNTY DISTRICT ATTORNEY",
    "KINGS CO SO": "KINGS COUNTY SHERIFF'S OFFICE",
    "KINGSBURG PD": "KINGSBURG POLICE DEPARTMENT",
    "LA HABRA PD": "LA HABRA POLICE DEPARTMENT",
    "LA MESA PD": "LA MESA POLICE DEPARTMENT",
    "LA PALMA PD": "LA PALMA POLICE DEPARTMENT",
    "LA VERNE PD": "LA VERNE POLICE DEPARTMENT",
    "LAFAYETTE PD": "LAFAYETTE POLICE DEPARTMENT",
    "LAKE CO DA": "LAKE COUNTY DISTRICT ATTORNEY",
    "LAKE CO SO": "LAKE COUNTY SHERIFF'S OFFICE",
    "LAKE ELSINORE PD": "LAKE ELSINORE POLICE DEPARTMENT",
    "LAKEPORT PD": "LAKEPORT POLICE DEPARTMENT",
    "LASSEN CO SO": "LASSEN COUNTY SHERIFF'S OFFICE",
    "LATHROP PD": "LATHROP POLICE DEPARTMENT",
    "LAWNDALE PD": "LAWNDALE POLICE DEPARTMENT",
    "LAYTONVILLE PD": "LAYTONVILLE POLICE DEPARTMENT",
    "LINDSAY DPS": "LINDSAY DEPARTMENT OF PUBLIC SAFETY",
    "LIVERMORE PD": "LIVERMORE POLICE DEPARTMENT",
    "LODI PD": "LODI POLICE DEPARTMENT",
    "LOMPOC PD": "LOMPOC POLICE DEPARTMENT",
    "LONG BEACH PD": "LONG BEACH POLICE DEPARTMENT",
    "LOS ALTOS PD": "LOS ALTOS POLICE DEPARTMENT",
    "LOS ANGELES CO DA": "LOS ANGELES COUNTY DISTRICT ATTORNEY",
    "LOS ANGELES CO METRO TRNS": "LOS ANGELES COUNTY METRO TRNS",
    "LOS ANGELES CO SD": "LOS ANGELES COUNTY SHERIFF'S DEPARTMENT",
    "LOS ANGELES PD": "LOS ANGELES POLICE DEPARTMENT",
    "LOS ANGELES SCHOOL PD": "LOS ANGELES SCHOOL POLICE DEPARTMENT",
    "LOS ANGELES WORLD AIRPORTS PD": "LOS ANGELES WORLD AIRPORTS POLICE DEPARTMENT",
    "LOS BANOS PD": "LOS BANOS POLICE DEPARTMENT",
    "LOS GATOS PD": "LOS GATOS POLICE DEPARTMENT",
    "LYNWOOD PD": "LYNWOOD POLICE DEPARTMENT",
    "MADERA CO DA": "MADERA COUNTY DISTRICT ATTORNEY",
    "MADERA CO SD": "MADERA COUNTY SHERIFF'S DEPARTMENT",
    "MADERA PD": "MADERA POLICE DEPARTMENT",
    "MARIN CO DA": "MARIN COUNTY DISTRICT ATTORNEY",
    "MARIN CO SO": "MARIN COUNTY SHERIFF'S OFFICE",
    "MARINA PD": "MARINA POLICE DEPARTMENT",
    "MARIPOSA CO SO": "MARIPOSA COUNTY SHERIFF'S OFFICE",
    "MARTINEZ PD": "MARTINEZ POLICE DEPARTMENT",
    "MARYSVILLE PD": "MARYSVILLE POLICE DEPARTMENT",
    "MAYWOOD PD": "MAYWOOD POLICE DEPARTMENT",
    "MENDOCINO CO DA": "MENDOCINO COUNTY DISTRICT ATTORNEY",
    "MENDOCINO CO SO": "MENDOCINO COUNTY SHERIFF'S OFFICE",
    "MENDOTA PD": "MENDOTA POLICE DEPARTMENT",
    "MENLO PARK PD": "MENLO PARK POLICE DEPARTMENT",
    "MERCED CO DA": "MERCED COUNTY DISTRICT ATTORNEY",
    "MERCED CO SO": "MERCED COUNTY SHERIFF'S OFFICE",
    "MERCED PD": "MERCED POLICE DEPARTMENT",
    "MILLBRAE PD": "MILLBRAE POLICE DEPARTMENT",
    "MILPITAS PD": "MILPITAS POLICE DEPARTMENT",
    "MISSION VIEJO PD": "MISSION VIEJO POLICE DEPARTMENT",
    "MODESTO PD": "MODESTO POLICE DEPARTMENT",
    "MONO CO SO": "MONO COUNTY SHERIFF'S OFFICE",
    "MONROVIA PD": "MONROVIA POLICE DEPARTMENT",
    "MONTCLAIR PD": "MONTCLAIR POLICE DEPARTMENT",
    "MONTEBELLO PD": "MONTEBELLO POLICE DEPARTMENT",
    "MONTEREY CO DA": "MONTEREY COUNTY DISTRICT ATTORNEY",
    "MONTEREY CO SO": "MONTEREY COUNTY SHERIFF'S OFFICE",
    "MONTEREY PD": "MONTEREY POLICE DEPARTMENT",
    "MOORPARK PD": "MOORPARK POLICE DEPARTMENT",
    "MORAGA-ORINDA PD": "MORAGA-ORINDA POLICE DEPARTMENT",
    "MORENO VALLEY PD": "MORENO VALLEY POLICE DEPARTMENT",
    "MORGAN HILL PD": "MORGAN HILL POLICE DEPARTMENT",
    "MORRO BAY PD": "MORRO BAY POLICE DEPARTMENT",
    "MOUNTAIN VIEW PD": "MOUNTAIN VIEW POLICE DEPARTMENT",
    "MT SHASTA PD": "MT SHASTA POLICE DEPARTMENT",
    "MURRIETA PD": "MURRIETA POLICE DEPARTMENT",
    "NAPA CO SO": "NAPA COUNTY SHERIFF'S OFFICE",
    "NAPA PD": "NAPA POLICE DEPARTMENT",
    "NATIONAL CITY PD": "NATIONAL CITY POLICE DEPARTMENT",
    "NEVADA CO SO": "NEVADA COUNTY SHERIFF'S OFFICE",
    "NEVADA CITY PD": "NEVADA CITY POLICE DEPARTMENT",
    "NEWMAN PD": "NEWMAN POLICE DEPARTMENT",
    "NORCO PD": "NORCO POLICE DEPARTMENT",
    "NORWALK PD": "NORWALK POLICE DEPARTMENT",
    "NOVATO PD": "NOVATO POLICE DEPARTMENT",
    "OAKDALE PD": "OAKDALE POLICE DEPARTMENT",
    "OAKLAND PD": "OAKLAND POLICE DEPARTMENT",
    "OCEANSIDE PD": "OCEANSIDE POLICE DEPARTMENT",
    "ONTARIO PD": "ONTARIO POLICE DEPARTMENT",
    "ORANGE CO DA": "ORANGE COUNTY DISTRICT ATTORNEY",
    "ORANGE CO SD/CORONER": "ORANGE COUNTY SHERIFF'S DEPARTMENT/CORONER",
    "ORANGE PD": "ORANGE POLICE DEPARTMENT",
    "ORINDA PD": "ORINDA POLICE DEPARTMENT",
    "OROVILLE PD": "OROVILLE POLICE DEPARTMENT",
    "OXNARD PD": "OXNARD POLICE DEPARTMENT",
    "PACIFIC GROVE PD": "PACIFIC GROVE POLICE DEPARTMENT",
    "PACIFICA PD": "PACIFICA POLICE DEPARTMENT",
    "PALM SPRINGS PD": "PALM SPRINGS POLICE DEPARTMENT",
    "PALMDALE PD": "PALMDALE POLICE DEPARTMENT",
    "PALO ALTO PD": "PALO ALTO POLICE DEPARTMENT",
    "PARADISE PD": "PARADISE POLICE DEPARTMENT",
    "PASADENA PD": "PASADENA POLICE DEPARTMENT",
    "PASO ROBLES PD": "PASO ROBLES POLICE DEPARTMENT",
    "PETALUMA PD": "PETALUMA POLICE DEPARTMENT",
    "PIEDMONT PD": "PIEDMONT POLICE DEPARTMENT",
    "PISMO BEACH PD": "PISMO BEACH POLICE DEPARTMENT",
    "PITTSBURG PD": "PITTSBURG POLICE DEPARTMENT",
    "PLACENTIA PD": "PLACENTIA POLICE DEPARTMENT",
    "PLACER COUNTY SO": "PLACER COUNTY SHERIFF'S OFFICE",
    "PLACERVILLE PD": "PLACERVILLE POLICE DEPARTMENT",
    "PLEASANT HILL PD": "PLEASANT HILL POLICE DEPARTMENT",
    "PLEASANTON PD": "PLEASANTON POLICE DEPARTMENT",
    "POINT ARENA PD": "POINT ARENA POLICE DEPARTMENT",
    "POMONA PD": "POMONA POLICE DEPARTMENT",
    "PORT HUENEME PD": "PORT HUENEME POLICE DEPARTMENT",
    "PORTERVILLE PD": "PORTERVILLE POLICE DEPARTMENT",
    "RANCHO CORDOVA PD": "RANCHO CORDOVA POLICE DEPARTMENT",
    "RANCHO CUCAMONGA PD": "RANCHO CUCAMONGA POLICE DEPARTMENT",
    "RANCHO PALOS VERDES PD": "RANCHO PALOS VERDES POLICE DEPARTMENT",
    "RED BLUFF PD": "RED BLUFF POLICE DEPARTMENT",
    "REDDING PD": "REDDING POLICE DEPARTMENT",
    "REDLANDS PD": "REDLANDS POLICE DEPARTMENT",
    "REDONDO BEACH PD": "REDONDO BEACH POLICE DEPARTMENT",
    "REDWOOD CITY PD": "REDWOOD CITY POLICE DEPARTMENT",
    "RIALTO PD": "RIALTO POLICE DEPARTMENT",
    "RICHMOND PD": "RICHMOND POLICE DEPARTMENT",
    "RIDGECREST PD": "RIDGECREST POLICE DEPARTMENT",
    "RIO DELL PD": "RIO DELL POLICE DEPARTMENT",
    "RIO VISTA PD": "RIO VISTA POLICE DEPARTMENT",
    "RIVERSIDE CO MAR,DESERT": "RIVERSIDE COUNTY MAR,DESERT",
    "RIVERSIDE CO MAR,RVRSIDE": "RIVERSIDE COUNTY MAR,RVRSIDE",
    "RIVERSIDE CO SD": "RIVERSIDE COUNTY SHERIFF'S DEPARTMENT",
    "RIVERSIDE PD": "RIVERSIDE POLICE DEPARTMENT",
    "ROCKLIN PD": "ROCKLIN POLICE DEPARTMENT",
    "ROHNERT PARK DPS": "ROHNERT PARK DEPARTMENT OF PUBLIC SAFETY",
    "ROSEVILLE PD": "ROSEVILLE POLICE DEPARTMENT",
    "SACRAMENTO CO DA": "SACRAMENTO COUNTY DISTRICT ATTORNEY",
    "SACRAMENTO CO MARSHAL": "SACRAMENTO COUNTY MARSHAL",
    "SACRAMENTO CO SD": "SACRAMENTO COUNTY SHERIFF'S DEPARTMENT",
    "SACRAMENTO PD": "SACRAMENTO POLICE DEPARTMENT",
    "SALINAS PD": "SALINAS POLICE DEPARTMENT",
    "SAN ANDREAS PD": "SAN ANDREAS POLICE DEPARTMENT",
    "SAN BERNARDINO CO DA": "SAN BERNARDINO COUNTY DISTRICT ATTORNEY",
    "SAN BERNARDINO CO SD": "SAN BERNARDINO COUNTY SHERIFF'S DEPARTMENT",
    "SAN BERNARDINO PD": "SAN BERNARDINO POLICE DEPARTMENT",
    "SAN BUENAVENTURA PD": "SAN BUENAVENTURA POLICE DEPARTMENT",
    "SAN DIEGO CO DA": "SAN DIEGO COUNTY DISTRICT ATTORNEY",
    "SAN DIEGO CO MARSHAL": "SAN DIEGO COUNTY MARSHAL",
    "SAN DIEGO CO SD": "SAN DIEGO COUNTY SHERIFF'S DEPARTMENT",
    "SAN DIEGO PD": "SAN DIEGO POLICE DEPARTMENT",
    "SAN FRANCISCO CO DA": "SAN FRANCISCO COUNTY DISTRICT ATTORNEY",
    "SAN FRANCISCO CO SO": "SAN FRANCISCO COUNTY SHERIFF'S OFFICE",
    "SAN FRANCISCO PD": "SAN FRANCISCO POLICE DEPARTMENT",
    "SAN JOAQUIN CO DA": "SAN JOAQUIN COUNTY DISTRICT ATTORNEY",
    "SAN JOAQUIN CO SD": "SAN JOAQUIN COUNTY SHERIFF'S DEPARTMENT",
    "SAN JOSE PD": "SAN JOSE POLICE DEPARTMENT",
    "SAN LEANDRO PD": "SAN LEANDRO POLICE DEPARTMENT",
    "SAN LUIS OBISPO CO DA": "SAN LUIS OBISPO COUNTY DISTRICT ATTORNEY",
    "SAN LUIS OBISPO CO SO": "SAN LUIS OBISPO COUNTY SHERIFF'S OFFICE",
    "SAN LUIS OBISPO PD": "SAN LUIS OBISPO POLICE DEPARTMENT",
    "SAN MARCOS PD": "SAN MARCOS POLICE DEPARTMENT",
    "SAN MARINO PD": "SAN MARINO POLICE DEPARTMENT",
    "SAN MATEO CO DA": "SAN MATEO COUNTY DISTRICT ATTORNEY",
    "SAN MATEO CO SHERIFF'S OFFICE": "SAN MATEO COUNTY SHERIFF'S OFFICE",
    "SAN MATEO PD": "SAN MATEO POLICE DEPARTMENT",
    "SAN PABLO PD": "SAN PABLO POLICE DEPARTMENT",
    "SAN RAMON PD": "SAN RAMON POLICE DEPARTMENT",
    "SANTA ANA PD": "SANTA ANA POLICE DEPARTMENT",
    "SANTA ANA UNIF SCHL DIST PD": "SANTA ANA UNIFIED SCHOOL DISTRICT POLICE DEPARTMENT",
    "SANTA BARBARA CO DA": "SANTA BARBARA COUNTY DISTRICT ATTORNEY",
    "SANTA BARBARA CO SO": "SANTA BARBARA COUNTY SHERIFF'S OFFICE",
    "SANTA BARBARA PD": "SANTA BARBARA POLICE DEPARTMENT",
    "SANTA CLARA CO DA": "SANTA CLARA COUNTY DISTRICT ATTORNEY",
    "SANTA CLARA CO SO": "SANTA CLARA COUNTY SHERIFF'S OFFICE",
    "SANTA CLARA PD": "SANTA CLARA POLICE DEPARTMENT",
    "SANTA CRUZ CO DA": "SANTA CRUZ COUNTY DISTRICT ATTORNEY",
    "SANTA CRUZ CO SO": "SANTA CRUZ COUNTY SHERIFF'S OFFICE",
    "SANTA CRUZ PD": "SANTA CRUZ POLICE DEPARTMENT",
    "SANTA MONICA PD": "SANTA MONICA POLICE DEPARTMENT",
    "SANTA ROSA PD": "SANTA ROSA POLICE DEPARTMENT",
    "SARATOGA PD": "SARATOGA POLICE DEPARTMENT",
    "SEASIDE PD": "SEASIDE POLICE DEPARTMENT",
    "SELMA PD": "SELMA POLICE DEPARTMENT",
    "SHASTA CO DA": "SHASTA COUNTY DISTRICT ATTORNEY",
    "SHASTA CO SO": "SHASTA COUNTY SHERIFF'S OFFICE",
    "SIGNAL HILL PD": "SIGNAL HILL POLICE DEPARTMENT",
    "SISKIYOU CO SO": "SISKIYOU COUNTY SHERIFF'S OFFICE",
    "SOLANO CO DA": "SOLANO COUNTY DISTRICT ATTORNEY",
    "SOLANO CO SO": "SOLANO COUNTY SHERIFF'S OFFICE",
    "SONOMA CO DA": "SONOMA COUNTY DISTRICT ATTORNEY",
    "SONOMA CO SO": "SONOMA COUNTY SHERIFF'S OFFICE",
    "SONORA PD": "SONORA POLICE DEPARTMENT",
    "SOUTH GATE PD": "SOUTH GATE POLICE DEPARTMENT",
    "SOUTH LAKE TAHOE PD": "SOUTH LAKE TAHOE POLICE DEPARTMENT",
    "SOUTH PASADENA PD": "SOUTH PASADENA POLICE DEPARTMENT",
    "SOUTH SAN FRANCISCO PD": "SOUTH SAN FRANCISCO POLICE DEPARTMENT",
    "ST HELENA PD": "ST HELENA POLICE DEPARTMENT",
    "STANISLAUS CO DA": "STANISLAUS COUNTY DISTRICT ATTORNEY",
    "STANISLAUS CO SD": "STANISLAUS COUNTY SHERIFF'S DEPARTMENT",
    "STOCKTON PD": "STOCKTON POLICE DEPARTMENT",
    "SUISUN CITY PD": "SUISUN CITY POLICE DEPARTMENT",
    "SUNNYVALE DPS": "SUNNYVALE DEPARTMENT OF PUBLIC SAFETY",
    "SUSANVILLE PD": "SUSANVILLE POLICE DEPARTMENT",
    "SUTTER CO SO": "SUTTER COUNTY SHERIFF'S OFFICE",
    "TEHAMA CO SO": "TEHAMA COUNTY SHERIFF'S OFFICE",
    "TEMECULA PD": "TEMECULA POLICE DEPARTMENT",
    "THOUSAND OAKS PD": "THOUSAND OAKS POLICE DEPARTMENT",
    "TIBURON PD": "TIBURON POLICE DEPARTMENT",
    "TRACY PD": "TRACY POLICE DEPARTMENT",
    "TRINITY CO SO": "TRINITY COUNTY SHERIFF'S OFFICE",
    "TULARE CO DA": "TULARE COUNTY DISTRICT ATTORNEY",
    "TULARE CO SO": "TULARE COUNTY SHERIFF'S OFFICE",
    "TULARE PD": "TULARE POLICE DEPARTMENT",
    "TUOLUMNE CO SO": "TUOLUMNE COUNTY SHERIFF'S OFFICE",
    "TURLOCK PD": "TURLOCK POLICE DEPARTMENT",
    "TUSTIN PD": "TUSTIN POLICE DEPARTMENT",
    "UC BERKELEY PD": "UNIVERSITY OF CALIFORNIA BERKELEY POLICE DEPARTMENT",
    "UC DAVIS PD": "UNIVERSITY OF CALIFORNIA DAVIS POLICE DEPARTMENT",
    "UC IRVINE PD": "UNIVERSITY OF CALIFORNIA IRVINE POLICE DEPARTMENT",
    "UC LOS ANGELES PD": "UNIVERSITY OF CALIFORNIA LOS ANGELES POLICE DEPARTMENT",
    "UC MERCED PD": "UNIVERSITY OF CALIFORNIA MERCED POLICE DEPARTMENT",
    "UC RIVERSIDE PD": "UNIVERSITY OF CALIFORNIA RIVERSIDE POLICE DEPARTMENT",
    "UC SAN DIEGO PD": "UNIVERSITY OF CALIFORNIA SAN DIEGO POLICE DEPARTMENT",
    "UC SAN FRANCISCO PD": "UNIVERSITY OF CALIFORNIA SAN FRANCISCO POLICE DEPARTMENT",
    "UC SANTA BARBARA PD": "UNIVERSITY OF CALIFORNIA SANTA BARBARA POLICE DEPARTMENT",
    "UC SANTA CRUZ PD": "UNIVERSITY OF CALIFORNIA SANTA CRUZ POLICE DEPARTMENT",
    "UKIAH PD": "UKIAH POLICE DEPARTMENT",
    "UNION CITY PD": "UNION CITY POLICE DEPARTMENT",
    "UPLAND PD": "UPLAND POLICE DEPARTMENT",
    "VACAVILLE PD": "VACAVILLE POLICE DEPARTMENT",
    "VALLEJO PD": "VALLEJO POLICE DEPARTMENT",
    "VENTURA CO DA": "VENTURA COUNTY DISTRICT ATTORNEY",
    "VENTURA CO SO": "VENTURA COUNTY SHERIFF'S OFFICE",
    "VENTURA PD": "VENTURA POLICE DEPARTMENT",
    "VICTORVILLE PD": "VICTORVILLE POLICE DEPARTMENT",
    "VISALIA PD": "VISALIA POLICE DEPARTMENT",
    "VISTA PD": "VISTA POLICE DEPARTMENT",
    "WALNUT CREEK PD": "WALNUT CREEK POLICE DEPARTMENT",
    "WASCO PD": "WASCO POLICE DEPARTMENT",
    "WATSONVILLE PD": "WATSONVILLE POLICE DEPARTMENT",
    "WEST COVINA PD": "WEST COVINA POLICE DEPARTMENT",
    "WEST HOLLYWOOD PD": "WEST HOLLYWOOD POLICE DEPARTMENT",
    "WEST SACRAMENTO PD": "WEST SACRAMENTO POLICE DEPARTMENT",
    "WESTMINSTER PD": "WESTMINSTER POLICE DEPARTMENT",
    "WHITTIER PD": "WHITTIER POLICE DEPARTMENT",
    "WILLIAMS PD": "WILLIAMS POLICE DEPARTMENT",
    "WILLITS PD": "WILLITS POLICE DEPARTMENT",
    "WILLOWS PD": "WILLOWS POLICE DEPARTMENT",
    "WINTON PD": "WINTON POLICE DEPARTMENT",
    "WOODLAND PD": "WOODLAND POLICE DEPARTMENT",
    "YOLO CO DA": "YOLO COUNTY DISTRICT ATTORNEY",
    "YOLO CO SO": "YOLO COUNTY SHERIFF'S OFFICE",
    "YREKA PD": "YREKA POLICE DEPARTMENT",
    "YUBA CO SO": "YUBA COUNTY SHERIFF'S OFFICE",
    "YUBA COMMUNITY COLL DIST PD": "YUBA COMMUNITY COLL DISTRICT POLICE DEPARTMENT",
    "YUCAIPA PD": "YUCAIPA POLICE DEPARTMENT",
}


def clean_leo_agency(raw_name):
    """Resolve LEO agency name from lookup table, with rule-based fallback."""
    if pd.isna(raw_name):
        return ""
    s = str(raw_name).strip()
    key = s.upper().strip()
    if key in LEO_AGENCY_MAP:
        return LEO_AGENCY_MAP[key]
    # Fallback rule-based expansions
    s_up = key
    # Expand common abbreviations
    s_up = re.sub(r'\bPD\b', 'POLICE DEPARTMENT', s_up)
    s_up = re.sub(r'\bSO\b', "SHERIFF'S OFFICE", s_up)
    s_up = re.sub(r'\bSD\b', "SHERIFF'S DEPARTMENT", s_up)
    s_up = re.sub(r'\bDPS\b', 'DEPARTMENT OF PUBLIC SAFETY', s_up)
    s_up = re.sub(r'\bDA\b', 'DISTRICT ATTORNEY', s_up)
    s_up = re.sub(r'\bCO\b', 'COUNTY', s_up)
    s_up = re.sub(r'\bCA\b', 'CALIFORNIA', s_up)
    s_up = re.sub(r'\bDEPT\b', 'DEPARTMENT', s_up)
    s_up = re.sub(r'\bSVCS?\b', 'SERVICES', s_up)
    s_up = re.sub(r'\s+', ' ', s_up).strip()
    return s_up


# ---------------------------------------------------------------------------
# PART 1: Process LEO data (CPRA POST xlsx / cached csv)
# ---------------------------------------------------------------------------
print("Loading LEO data...")
# Use pre-converted CSV if available (faster); fall back to xlsx
leo_csv_path = os.path.join(INPUT_DIR, "leo_data.csv")
leo_xlsx_path = os.path.join(INPUT_DIR, "CPRA_R000301-011425__ADHOC-809.xlsx")
if os.path.exists(leo_csv_path):
    leo_raw = pd.read_csv(leo_csv_path, dtype=str, low_memory=False)
else:
    leo_raw = pd.read_excel(leo_xlsx_path, dtype=str)

leo_raw.columns = [c.strip() for c in leo_raw.columns]

# person_nbr = POST_ID; strip whitespace, lowercase
leo_raw["person_nbr"] = leo_raw["POST_ID"].astype(str).str.strip().str.lower()

# Drop rows with no person_nbr
leo_raw = leo_raw[leo_raw["person_nbr"].notna() & (leo_raw["person_nbr"] != "") & (leo_raw["person_nbr"] != "nan")]

# Parse names using nameparser — only parse unique names for speed
print("Parsing LEO names...")

def parse_leo_name(name_str):
    s = str(name_str).strip() if pd.notna(name_str) else ""
    if not s or s == "nan":
        return ("", "", "", "")
    n = HumanName(s)
    return (
        n.first.upper() if n.first else "",
        n.middle.upper() if n.middle else "",
        n.last.upper() if n.last else "",
        n.suffix.upper() if n.suffix else "",
    )

unique_names = leo_raw["officer_name"].fillna("").unique()
name_cache = {nm: parse_leo_name(nm) for nm in unique_names}
parsed_tuples = leo_raw["officer_name"].fillna("").map(name_cache)
leo_raw["first_name"] = [t[0] for t in parsed_tuples]
leo_raw["middle_name"] = [t[1] for t in parsed_tuples]
leo_raw["last_name"] = [t[2] for t in parsed_tuples]
leo_raw["suffix"] = [t[3] for t in parsed_tuples]

# Dates — vectorized for speed
leo_raw["start_date"] = (
    pd.to_datetime(leo_raw["employment_start_date"], errors="coerce")
    .dt.strftime("%Y-%m-%d")
    .fillna("")
)
leo_raw["end_date"] = (
    pd.to_datetime(leo_raw["employment_end_date"], errors="coerce")
    .dt.strftime("%Y-%m-%d")
    .fillna("")
)

# Drop rows with empty start_date
leo_raw = leo_raw[leo_raw["start_date"] != ""]

# Agency names — use dict lookup for speed, fallback for unmapped
print("Cleaning LEO agency names...")
agency_key = leo_raw["agency"].astype(str).str.strip().str.upper()
# Build fallback for unmapped agencies using rule-based expansion
def fallback_agency(key):
    import re
    s = key
    s = re.sub(r'\bPD\b', 'POLICE DEPARTMENT', s)
    s = re.sub(r'\bSO\b', "SHERIFF'S OFFICE", s)
    s = re.sub(r'\bSD\b', "SHERIFF'S DEPARTMENT", s)
    s = re.sub(r'\bDPS\b', 'DEPARTMENT OF PUBLIC SAFETY', s)
    s = re.sub(r'\bDA\b', 'DISTRICT ATTORNEY', s)
    s = re.sub(r'\bCO\b', 'COUNTY', s)
    s = re.sub(r'\bCA\b', 'CALIFORNIA', s)
    s = re.sub(r'\bDEPT\b', 'DEPARTMENT', s)
    s = re.sub(r'\bSVCS?\b', 'SERVICES', s)
    return re.sub(r'\s+', ' ', s).strip()

# Build full lookup including fallbacks for all unique values
unique_agencies = agency_key.unique()
agency_resolved = {}
for k in unique_agencies:
    if k in LEO_AGENCY_MAP:
        agency_resolved[k] = LEO_AGENCY_MAP[k]
    elif not k or k == "NAN":
        agency_resolved[k] = ""
    else:
        agency_resolved[k] = fallback_agency(k)
leo_raw["agency_name"] = agency_key.map(agency_resolved)

# separation_reason from separation_code
leo_raw["separation_code_str"] = leo_raw["separation_code"].astype(str).str.strip()
leo_raw["separation_reason"] = leo_raw["separation_code_str"].map(SEPARATION_CODE_MAP).fillna("")

# rank - keep as-is (uppercase already in source)
leo_raw["rank"] = leo_raw["rank"].astype(str).str.strip().str.upper()
leo_raw.loc[leo_raw["rank"] == "NAN", "rank"] = ""

# full_name
leo_raw["full_name"] = leo_raw["officer_name"].astype(str).str.strip().str.upper()

# type
leo_raw["type"] = "POLICE"

# Select and order columns for LEO
leo_cols = [
    "person_nbr", "first_name", "middle_name", "last_name", "suffix",
    "full_name", "agency_name", "start_date", "end_date",
    "rank", "separation_reason", "type",
]
leo_df = leo_raw[leo_cols].copy()

# Filter out non-agency strings
NON_AGENCY = {"", "nan", "application denied", "application purged", "pending", "unknown", "n/a"}
leo_df = leo_df[~leo_df["agency_name"].str.strip().str.lower().isin(NON_AGENCY)]

print(f"LEO rows after cleaning: {len(leo_df)}")

# ---------------------------------------------------------------------------
# PART 2: Process Corrections data (CDCR csv)
# ---------------------------------------------------------------------------
print("Loading Corrections data...")
corr_path = os.path.join(INPUT_DIR, "PDSQ118B-C_CDCR Appts&Seps 2005-2023_Final.csv")
corr_raw = pd.read_csv(corr_path, dtype=str)

corr_raw.columns = [c.strip() for c in corr_raw.columns]

# person_nbr = UNIQUE ID
corr_raw["person_nbr"] = corr_raw["UNIQUE ID"].astype(str).str.strip()

# Names: LAST NAME, FIRST NAME (which includes middle initial)
corr_raw["last_name"] = corr_raw["LAST NAME"].astype(str).str.strip().str.upper()
# First name column includes middle initial after space
first_mi = corr_raw["FIRST NAME"].astype(str).str.strip().str.upper()

# Vectorized first/middle split
first_mi_split = first_mi.str.split(r'\s+', n=1, expand=True)
corr_raw["first_name"] = first_mi_split[0].fillna("").str.strip()
corr_raw["middle_name"] = first_mi_split[1].fillna("").str.strip()

# Build full_name
corr_raw["full_name"] = (
    corr_raw["first_name"] + " " + corr_raw["middle_name"] + " " + corr_raw["last_name"]
).str.strip()

# Extract facility code from POSITION NUMBER (first segment, zero-pad to 3)
def extract_facility_code(pos):
    s = str(pos).strip()
    parts = s.split("-")
    if parts:
        try:
            return parts[0].strip().zfill(3)
        except Exception:
            return ""
    return ""

corr_raw["facility_code"] = (
    corr_raw["POSITION NUMBER"].astype(str).str.strip()
    .str.split("-").str[0].str.strip().str.zfill(3)
)

# Build code -> canonical facility name mapping (most frequent per code)
# Format for agency_name: "NNN: CANONICAL NAME" matching groundtruth
# First build a code -> gt-style name lookup from the data itself
facility_name_raw = corr_raw["FACILITY NAME"].astype(str).str.strip().str.upper()

# Build code -> most-frequent raw facility name
code_name_map = (
    corr_raw.assign(facility_name_upper=facility_name_raw)
    .groupby("facility_code")["facility_name_upper"]
    .agg(lambda x: x.value_counts().index[0])
    .to_dict()
)

# Map raw facility names to groundtruth-style canonical names
# GT format: "NNN: CANONICAL NAME"
# We'll use the raw FACILITY NAME cleaned up but keep the code prefix as GT does
RAW_TO_GT_FACILITY = {
    "025": ("025", "MULE CREEK STATE PRISON"),
    "026": ("026", "AVENAL STATE PRISON"),
    "027": ("027", "CSP - LOS ANGELES COUNTY"),
    "028": ("028", "CHUCKAWALLA VALLEY STATE PRIS -AKA- CHUCKAWALLA VALLEY STATE PRISO"),
    "030": ("030", "R J DONOVAN CORRECTIONS FACILITY"),
    "037": ("037", "CALIFORNIA STATE PRISON - LOS ANGELE -AKA- CCHCS-CSP LOS ANGELES"),
    "041": ("041", "CCHCS-CHUCKAWALLA VALLEY SP -AKA- CHUCKAWALLA VALLEY STATE PRIS"),
    "042": ("042", "CCHCS-HEADQUARTERS -AKA- HEADQUARTERS"),
    "048": ("048", "RA MCGEE CORRECTIONS TRAIN CENTER -AKA- RICHARD A MCGEE CORRECTIONS TR CENTER"),
    "054": ("054", "CALIFORNIA CORRECTIONAL INSTITUTION"),
    "056": ("056", "CALIFORNIA MEN'S COLONY"),
    "061": ("061", "PAROLE & COMMUNITY SERVICES DIVISION"),
    "064": ("064", "NORTHERN REGION"),
    "065": ("065", "CDCR/ADMINISTRATION -AKA- CORRECTIONS/ADMINISTRATION"),
    "068": ("068", "CALIFORNIA CORRECTIONAL CENTER"),
    "071": ("071", "FOLSOM STATE PRISON"),
    "076": ("076", "CALIFORNIA MEDICAL FACILITY"),
    "079": ("079", "REHABILITATION CENTER"),
    "080": ("080", "CALIFORNIA INSTITUTION FOR MEN"),
    "083": ("083", "CENTRAL REGION"),
    "084": ("084", "CALIFORNIA STATE PRISON - CORCORAN"),
    "086": ("086", "CALIFORNIA INSTITUTION FOR WOMEN"),
    "089": ("089", "CCHCS-SUSBTANCE ABUSE TRMT FAC"),
    "091": ("091", "SOUTHERN REGION"),
    "095": ("095", "SAN QUENTIN STATE PRISON"),
    "098": ("098", "SAN QUENTIN STATE PRISON"),
    "099": ("099", "SIERRA CONSERVATION CENTER"),
    "101": ("101", "CORRECTIONAL TRAINING FACILIT -AKA- CORRECTIONAL TRAINING FACILITY"),
    "106": ("106", "DEUEL VOCATIONAL INSTITUTION"),
    "109": ("109", "CCHCS-DEUEL VOCATIONAL CENTER"),
    "110": ("110", "CDCR ADMIN -AKA- YOUTH AUTHORITY/ADMINISTRATION"),
    "113": ("113", "SOUTHERN RECEPTION CENTER"),
    "116": ("116", "CALIFORNIA CITY CORRECTIONAL FACILITY"),
    "123": ("123", "CCHCS-FOLSOM STATE PRISON -AKA- FOLSOM STATE PRISON"),
    "127": ("127", "EL PASO DE ROBLES SCHOOL"),
    "128": ("128", "CALIFORNIA INSTITUTION FOR WOMEN -AKA- CCHCS-CALIFORNIA INSTITUTION FOR WOMEN"),
    "131": ("131", "PRESTON SCHOOL OF INDUSTRY"),
    "133": ("133", "PINE GROVE YOUTH CONS CAMP"),
    "135": ("135", "VENTURA SCHOOL FOR GIRLS"),
    "138": ("138", "YOUTH TRAINING SCHOOL"),
    "140": ("140", "CDCR/CCHCS CALIFORNIA HEALTH CARE FAC -AKA- CDCR/CCHCS CALIFORNIA HEALTH CARE FACI"),
    "143": ("143", "NORTHERN CALIFORNIA YOUTH CENTER"),
    "146": ("146", "O. H. CLOSE SCHOOL"),
    "178": ("178", "CALIPATRIA STATE PRISON"),
    "180": ("180", "CALIFORNIA STATE PRISON - WASCO"),
    "182": ("182", "NORTH KERN STATE PRISON"),
    "190": ("190", "CALIFORNIA HEALTH CARE FACILITY"),
    "194": ("194", "CHADERJIAN SCHOOL"),
    "284": ("284", "CALIFORNIA STATE PRISON - SACRAMENTO"),
    "381": ("381", "CENTRAL CALIFORNIA WOMENS FACILITY"),
    "394": ("394", "PELICAN BAY STATE PRISON"),
    "403": ("403", "CENTINELA STATE PRISON"),
    "435": ("435", "PLEASANT VALLEY STATE PRISON"),
    "444": ("444", "IRONWOOD STATE PRISON"),
    "486": ("486", "CALIFORNIA MEDICAL FACILITY-PIP -AKA- CDCR-CALIFORNIA MEDICAL FACILITY-PIP"),
    "488": ("488", "CDCR-SALINAS VALLEY-PIP -AKA- SALINAS VALLEY - PIP"),
    "587": ("587", "SUBSTANCE ABUSE TREAT-CORCORA -AKA- SUBSTANCE ABUSE TREAT-CORCORAN"),
    "674": ("674", "CALIFORNIA STATE PRISON - SOLANO"),
    "915": ("915", "DELANO II STATE PRISON -AKA- KERN VALLEY STATE PRISON"),
    "919": ("919", "VALLEY STATE PRISON"),
    "934": ("934", "HIGH DESERT STATE PRISON"),
    "936": ("936", "SALINAS VALLEY STATE PRISON"),
}


def get_corrections_agency(facility_code, raw_facility):
    """Return 'NNN: CANONICAL NAME' for corrections agency."""
    if facility_code in RAW_TO_GT_FACILITY:
        code, name = RAW_TO_GT_FACILITY[facility_code]
        return f"{code}: {name}"
    # Fallback: use zero-padded code + cleaned raw name
    raw = str(raw_facility).strip().upper()
    return f"{facility_code}: {raw}"


# Build lookup for corrections agency names
unique_fc_fn = corr_raw[["facility_code", "FACILITY NAME"]].drop_duplicates()
fc_fn_map = {}
for _, row in unique_fc_fn.iterrows():
    fc = row["facility_code"]
    fn = row["FACILITY NAME"]
    fc_fn_map[(fc, str(fn).strip().upper())] = get_corrections_agency(fc, fn)

# Map using combined key
corr_raw["_fc_fn_key"] = list(zip(corr_raw["facility_code"], corr_raw["FACILITY NAME"].astype(str).str.strip().str.upper()))
corr_raw["agency_name"] = corr_raw["_fc_fn_key"].map(fc_fn_map)

# ---------------------------------------------------------------------------
# Build employment periods from APPOINTMENT + SEPARATION records
# Strategy: For each (person, position_number) pair, match appointments
# to separations. APPOINTMENT = start, SEPARATION = end.
# ---------------------------------------------------------------------------
print("Building corrections employment periods...")

corr_raw["trans_date"] = pd.to_datetime(corr_raw["TRANS EFF DATE"], errors="coerce")
corr_raw["type_of_trans"] = corr_raw["TYPE OF TRANSACTION"].astype(str).str.strip().str.upper()

# Normalize POSITION NUMBER: zero-pad the first segment to 3 digits
# e.g. "26-210-9662-902" -> "026-210-9662-902"
def normalize_pos(pos):
    s = str(pos).strip()
    parts = s.split("-")
    if len(parts) >= 1:
        parts[0] = parts[0].strip().zfill(3)
    return "-".join(parts)

corr_raw["pos_norm"] = corr_raw["POSITION NUMBER"].astype(str).apply(normalize_pos)

# For each (person, position_number) group:
# - start = min date of APPOINTMENT/CHANGE records
# - end   = max date of SEPARATION records (may be absent = still employed)
# - use demographics/agency from the first APPOINTMENT/CHANGE record

appts = corr_raw[corr_raw["type_of_trans"].isin(["APPOINTMENT", "CHANGE"])].copy()
seps = corr_raw[corr_raw["type_of_trans"] == "SEPARATION"].copy()

# Group appointments: take min date and associated metadata
appts_sorted = appts.sort_values(["person_nbr", "pos_norm", "trans_date"])
appt_first = appts_sorted.drop_duplicates(subset=["person_nbr", "pos_norm"], keep="first")

# Min start date per (person, position)
appt_min = (
    appts.groupby(["person_nbr", "pos_norm"])["trans_date"]
    .min()
    .reset_index()
    .rename(columns={"trans_date": "start_dt"})
)

# Max sep date per (person, position)
sep_max = (
    seps.groupby(["person_nbr", "pos_norm"])["trans_date"]
    .max()
    .reset_index()
    .rename(columns={"trans_date": "end_dt"})
)

# Merge metadata from first appointment
keep_cols = ["person_nbr", "pos_norm", "facility_code", "FACILITY NAME",
             "CLASS TITLE", "last_name", "first_name", "middle_name",
             "full_name", "agency_name"]
appt_meta = appt_first[keep_cols].copy()

# Build pairs: merge start dates + metadata + end dates
pairs = appt_min.merge(appt_meta, on=["person_nbr", "pos_norm"], how="left")
pairs = pairs.merge(sep_max, on=["person_nbr", "pos_norm"], how="left")

# Convert dates to strings — vectorized
pairs["start_date"] = pairs["start_dt"].dt.strftime("%Y-%m-%d").fillna("")
pairs["end_date"] = pairs["end_dt"].dt.strftime("%Y-%m-%d").fillna("")

# Drop rows with empty start_date
pairs = pairs[pairs["start_date"] != ""]

# rank = CLASS TITLE
pairs["rank"] = pairs["CLASS TITLE"].astype(str).str.strip().str.upper()
pairs.loc[pairs["rank"] == "NAN", "rank"] = ""

# type
pairs["type"] = "CORRECTIONS"

# Drop rows with empty start_date
pairs = pairs[pairs["start_date"] != ""]

# Select columns
corr_cols = [
    "person_nbr", "first_name", "middle_name", "last_name",
    "full_name", "agency_name", "start_date", "end_date",
    "rank", "type",
]
corr_df = pairs[corr_cols].copy()

# Dedup on person_nbr + agency_name + start_date
corr_df = corr_df.drop_duplicates(subset=["person_nbr", "agency_name", "start_date"])

print(f"Corrections rows after processing: {len(corr_df)}")

# ---------------------------------------------------------------------------
# PART 3: Concatenate LEO + Corrections
# ---------------------------------------------------------------------------
print("Concatenating LEO + Corrections...")

# Add suffix column to corrections (not available)
corr_df["suffix"] = ""
leo_df["separation_reason"] = leo_df["separation_reason"].fillna("")
corr_df["separation_reason"] = ""

combined = pd.concat([leo_df, corr_df], ignore_index=True, sort=False)

# Final cleanup
combined["person_nbr"] = combined["person_nbr"].astype(str).str.strip().str.lower()
combined["first_name"] = combined["first_name"].astype(str).str.strip()
combined["last_name"] = combined["last_name"].astype(str).str.strip()
combined["agency_name"] = combined["agency_name"].astype(str).str.strip()
combined["start_date"] = combined["start_date"].astype(str).str.strip()
combined["end_date"] = combined["end_date"].astype(str).str.strip()

# Ensure no NaT/None in date columns
combined["start_date"] = combined["start_date"].replace({"NaT": "", "None": "", "nan": ""})
combined["end_date"] = combined["end_date"].replace({"NaT": "", "None": "", "nan": ""})

# Drop rows with empty start_date (pipeline drops anyway)
combined = combined[combined["start_date"] != ""]

# Drop rows with no person_nbr
combined = combined[combined["person_nbr"].notna() & (combined["person_nbr"] != "") & (combined["person_nbr"] != "nan")]

# Dedup
dupe_before = combined.duplicated(subset=["person_nbr", "agency_name", "start_date"]).sum()
if dupe_before > 0:
    print(f"Dropping {dupe_before} duplicate rows")
    combined = combined.drop_duplicates(subset=["person_nbr", "agency_name", "start_date"])

print(f"Final combined rows: {len(combined)}")

# ---------------------------------------------------------------------------
# Validate
# ---------------------------------------------------------------------------
required = ["person_nbr", "first_name", "last_name", "agency_name", "start_date", "end_date"]
missing_cols = [c for c in required if c not in combined.columns]
assert not missing_cols, f"Missing required columns: {missing_cols}"

assert (combined["start_date"] != "").all(), "start_date must not be empty"

for col in required:
    empty_count = (combined[col].isna() | (combined[col] == "")).sum()
    if empty_count > 0:
        print(f"Warning: {col} has {empty_count} empty values ({empty_count/len(combined):.1%})")

# ---------------------------------------------------------------------------
# Write output
# ---------------------------------------------------------------------------
out_cols = [
    "person_nbr", "first_name", "middle_name", "last_name", "suffix",
    "full_name", "agency_name", "start_date", "end_date",
    "rank", "separation_reason", "type",
]
# Only include columns that exist
out_cols = [c for c in out_cols if c in combined.columns]

output_path = os.path.join(OUTPUT_DIR, "ca_index.csv")
combined[out_cols].to_csv(output_path, index=False)
print(f"Wrote {len(combined)} rows to {output_path}")
