from __future__ import annotations

import logging
import subprocess
from datetime import date

from pipeline.clean_runner import CleanResult


logger = logging.getLogger(__name__)


def build_pr_body(results: list[CleanResult]) -> str:
    lines = [
        "## Automated POST Data Update",
        "",
        f"**Date:** {date.today().isoformat()}",
        "",
        "| State | Year | Result | Ground Truth | Notes |",
        "|-------|------|--------|-------------|-------|",
    ]
    for r in results:
        if r.error:
            lines.append(
                f"| {r.state} | {r.year} | FAIL | — | `{r.error[:80]}` |"
            )
        else:
            gt = "Yes" if r.judge.has_groundtruth else "⚠️ No ground truth"
            lines.append(
                f"| {r.state} | {r.year} | {r.judge.overall} | {gt} | |"
            )

    lines += [""]
    for r in results:
        lines.append(f"## {r.state.upper()}/{r.year} judge report")
        if r.error:
            lines.append(f"```\n{r.error}\n```")
        elif r.judge and r.judge.raw:
            lines.append(r.judge.raw.strip())
        else:
            lines.append("_No judge report available._")
        lines.append("")

    lines += ["---", "_Generated by the automated rclone pipeline._"]
    return "\n".join(lines)


class PRGenerator:
    def __init__(self, repo_root: str = "."):
        self._repo_root = repo_root

    def _git(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args],
            cwd=self._repo_root,
            capture_output=True,
            text=True,
        )

    def commit_outputs(self, pairs: list[tuple[str, str]], branch: str) -> None:
        r = self._git("checkout", "-b", branch)
        if r.returncode != 0:
            raise RuntimeError(
                f"git checkout -b {branch} failed: {r.stderr.strip()}"
            )
        for state, year in pairs:
            r = self._git(
                "add",
                "--force",
                f"db/data/output/{state}/",
                f"states/{state}/{year}/src/clean.py",
                f"states/{state}/{year}/src/validate.py",
            )
            if r.returncode != 0:
                logger.warning(
                    "git add for %s/%s: %s", state, year, r.stderr.strip()
                )
        r = self._git(
            "add",
            "--force",
            "pipeline/data/manifest.json",
            "pipeline/data/registry.csv",
        )
        if r.returncode != 0:
            logger.warning("git add pipeline/data/: %s", r.stderr.strip())
        status = self._git("status", "--short")
        logger.info("git status before commit:\n%s", status.stdout.strip())
        label = ", ".join(f"{s}/{y}" for s, y in pairs)
        r = self._git(
            "commit", "-m", f"data: automated POST update for {label}"
        )
        if r.returncode != 0:
            raise RuntimeError(
                f"git commit failed: {r.stderr.strip() or r.stdout.strip()}"
            )

    def create_pr(
        self,
        branch: str,
        results: list[CleanResult],
        base: str = "main",
    ) -> None:
        r = self._git("push", "-u", "origin", branch)
        if r.returncode != 0:
            logger.error(
                "git push failed: %s", r.stderr.strip() or r.stdout.strip()
            )
            return
        label = ", ".join(f"{r.state}/{r.year}" for r in results)
        try:
            subprocess.run(
                [
                    "gh",
                    "pr",
                    "create",
                    "--title",
                    f"data: automated POST update — {label}",
                    "--body",
                    build_pr_body(results),
                    "--base",
                    base,
                    "--head",
                    branch,
                ],
                cwd=self._repo_root,
                check=True,
            )
        except FileNotFoundError:
            print("  gh CLI not found — skipping PR creation.")
        except subprocess.CalledProcessError as e:
            print(
                f"  gh pr create failed (exit {e.returncode})"
                " — skipping PR creation."
            )
