from __future__ import annotations

import subprocess
from datetime import date

from pipeline.clean_runner import CleanResult


def build_pr_body(results: list[CleanResult]) -> str:
    lines = [
        "## Automated POST Data Update",
        "",
        f"**Date:** {date.today().isoformat()}",
        "",
        "| State | Year | Result | Ground Truth | Notes |",
        "|-------|------|--------|-------------|-------|",
    ]
    for r in results:
        if r.error:
            lines.append(
                f"| {r.state} | {r.year} | FAIL | — "
                f"| `{r.error[:80]}` |"
            )
        else:
            gt = "Yes" if r.judge.has_groundtruth else "⚠️ No ground truth"
            lines.append(
                f"| {r.state} | {r.year} | {r.judge.overall} | {gt} | |"
            )

    for r in results:
        if r.judge and not r.judge.has_groundtruth:
            lines.append(
                f"\n> **{r.state}/{r.year}:** "
                f"No ground truth — manual review recommended."
            )

    lines += ["", "---", "_Generated by the automated rclone pipeline._"]
    return "\n".join(lines)


class PRGenerator:
    def __init__(self, repo_root: str = "."):
        self._repo_root = repo_root

    def _git(self, *args: str) -> subprocess.CompletedProcess:
        return subprocess.run(
            ["git", *args],
            cwd=self._repo_root,
            capture_output=True,
            text=True,
        )

    def commit_outputs(
        self, pairs: list[tuple[str, str]], branch: str
    ) -> None:
        self._git("checkout", "-b", branch)
        for state, year in pairs:
            self._git(
                "add",
                f"states/{state}/{year}/output/",
                f"states/{state}/{year}/src/clean.py",
                f"states/{state}/{year}/src/validate.py",
            )
        self._git(
            "add",
            "pipeline/data/manifest.json",
            "pipeline/data/registry.csv",
        )
        label = ", ".join(f"{s}/{y}" for s, y in pairs)
        self._git("commit", "-m", f"data: automated POST update for {label}")

    def create_pr(
        self,
        branch: str,
        results: list[CleanResult],
        base: str = "main",
    ) -> None:
        label = ", ".join(f"{r.state}/{r.year}" for r in results)
        try:
            subprocess.run(
                [
                    "gh", "pr", "create",
                    "--title", f"data: automated POST update — {label}",
                    "--body", build_pr_body(results),
                    "--base", base,
                    "--head", branch,
                ],
                cwd=self._repo_root,
                check=True,
            )
        except FileNotFoundError:
            print("  gh CLI not found — skipping PR creation.")
