# schema.yml
## these is a schema for the columns that are (relatively) consistent across states

schema:
  unique_citizen:
    columns:
      - name: uid
        description: >
          unique officer id
      - name: agency_name
        description: >
          name of the agency
      - name: employment_type
        description: >
          full-time, part-time, reserve, etc
      - name: agency_type
        description: >
          police, corrections, etc
